# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newroom_PL2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(800, 600)
        Main.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(247, 73, 75, 255), stop:0.997452 rgba(255, 189, 96, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 20, 801, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAutoFillBackground(False)
        self.title.setStyleSheet("background:none;")
        self.title.setScaledContents(True)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.credit = QtWidgets.QLabel(self.centralwidget)
        self.credit.setGeometry(QtCore.QRect(0, 560, 801, 31))
        self.credit.setStyleSheet("color:white;background-color:none;")
        self.credit.setAlignment(QtCore.Qt.AlignCenter)
        self.credit.setObjectName("credit")
        self.description = QtWidgets.QLabel(self.centralwidget)
        self.description.setGeometry(QtCore.QRect(0, 90, 801, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.description.setFont(font)
        self.description.setStyleSheet("background:none;")
        self.description.setAlignment(QtCore.Qt.AlignCenter)
        self.description.setObjectName("description")
        self.roomname_label = QtWidgets.QLabel(self.centralwidget)
        self.roomname_label.setGeometry(QtCore.QRect(0, 180, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.roomname_label.setFont(font)
        self.roomname_label.setStyleSheet("background:none;")
        self.roomname_label.setObjectName("roomname_label")
        self.roomname_input = QtWidgets.QLineEdit(self.centralwidget)
        self.roomname_input.setGeometry(QtCore.QRect(180, 180, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.roomname_input.setFont(font)
        self.roomname_input.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 170, 127, 176), stop:1 rgba(255, 255, 127, 187));\n"
"border:1px solid white; border-radius: 5px;")
        self.roomname_input.setText("")
        self.roomname_input.setObjectName("roomname_input")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 170, 801, 161))
        self.widget.setStyleSheet("border:2px solid white;background:none;\n"
"border-radius:5px;\n"
"")
        self.widget.setObjectName("widget")
        self.maxplayer_label = QtWidgets.QLabel(self.widget)
        self.maxplayer_label.setGeometry(QtCore.QRect(0, 90, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.maxplayer_label.setFont(font)
        self.maxplayer_label.setStyleSheet("background:none;border:none;")
        self.maxplayer_label.setObjectName("maxplayer_label")
        self.maxplayer_input = QtWidgets.QSpinBox(self.widget)
        self.maxplayer_input.setGeometry(QtCore.QRect(200, 90, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setKerning(True)
        self.maxplayer_input.setFont(font)
        self.maxplayer_input.setStyleSheet("border-radius:5px;")
        self.maxplayer_input.setWrapping(False)
        self.maxplayer_input.setFrame(True)
        self.maxplayer_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.maxplayer_input.setMinimum(2)
        self.maxplayer_input.setMaximum(20)
        self.maxplayer_input.setObjectName("maxplayer_input")
        self.createroom = QtWidgets.QPushButton(self.centralwidget)
        self.createroom.setGeometry(QtCore.QRect(292, 357, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.createroom.setFont(font)
        self.createroom.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 170, 127, 176), stop:1 rgba(255, 255, 127, 187));\n"
"color:white;")
        self.createroom.setObjectName("createroom")
        self.exit = QtWidgets.QLabel(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(730, 20, 55, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.exit.setFont(font)
        self.exit.setStyleSheet("QLabel {\n"
"background:none;\n"
"}\n"
"QLabel::hover {\n"
"background:none;\n"
"color:white;\n"
"}")
        self.exit.setAlignment(QtCore.Qt.AlignCenter)
        self.exit.setObjectName("exit")
        self.widget.raise_()
        self.title.raise_()
        self.credit.raise_()
        self.description.raise_()
        self.roomname_label.raise_()
        self.roomname_input.raise_()
        self.createroom.raise_()
        self.exit.raise_()
        Main.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Game Bầu Cua Online - New Room - PL2"))
        self.title.setText(_translate("Main", "TẠO PHÒNG MỚI"))
        self.credit.setText(_translate("Main", "Game made by MHP. You can buy me a cup of coffee through https://www.buymeacoffee.com/py.hacker.hieu, thank you very much."))
        self.description.setText(_translate("Main", "Bạn hãy điền đầy đủ thông tin"))
        self.roomname_label.setText(_translate("Main", "Tên Phòng:"))
        self.roomname_input.setPlaceholderText(_translate("Main", "Nhập tên phòng vào đây"))
        self.maxplayer_label.setText(_translate("Main", "Số người tối đa:"))
        self.createroom.setText(_translate("Main", "Tạo phòng"))
        self.exit.setText(_translate("Main", "X"))