# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tutorial.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(800, 600)
        Main.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(247, 73, 75, 255), stop:0.997452 rgba(255, 189, 96, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 30, 801, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAutoFillBackground(False)
        self.title.setStyleSheet("background:none;")
        self.title.setScaledContents(True)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.description = QtWidgets.QLabel(self.centralwidget)
        self.description.setGeometry(QtCore.QRect(0, 90, 801, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.description.setFont(font)
        self.description.setStyleSheet("background:none;")
        self.description.setAlignment(QtCore.Qt.AlignCenter)
        self.description.setObjectName("description")
        self.credit = QtWidgets.QLabel(self.centralwidget)
        self.credit.setGeometry(QtCore.QRect(0, 560, 801, 31))
        self.credit.setStyleSheet("color:white;background-color:none;")
        self.credit.setAlignment(QtCore.Qt.AlignCenter)
        self.credit.setObjectName("credit")
        self.tutorialtb = QtWidgets.QTextBrowser(self.centralwidget)
        self.tutorialtb.setGeometry(QtCore.QRect(40, 190, 731, 351))
        self.tutorialtb.setObjectName("tutorialtb")
        self.exit = QtWidgets.QLabel(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(730, 20, 55, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.exit.setFont(font)
        self.exit.setStyleSheet("QLabel {\n"
"background:none;\n"
"}\n"
"QLabel::hover {\n"
"background:none;\n"
"color:white;\n"
"}")
        self.exit.setAlignment(QtCore.Qt.AlignCenter)
        self.exit.setObjectName("exit")
        Main.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Game Bầu Cua Online - Opening Page"))
        self.title.setText(_translate("Main", "HƯỚNG DẪN"))
        self.description.setText(_translate("Main", "Bầu Cua Online Game"))
        self.exit.setText(_translate("Main", "X"))
        self.credit.setText(_translate("Main", "Game made by MHP. You can buy me a cup of coffee through https://www.buymeacoffee.com/py.hacker.hieu, thank you very much."))
        self.tutorialtb.setHtml(_translate("Main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Bầu Cua Online Game là gì?</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Bầu Cua Online Game là </span><span style=\" font-size:12pt; font-style:italic;\">một trò chơi mã nguồn mở</span><span style=\" font-size:12pt;\"> được làm bởi MHP nhân dịp Tết Quý Mão 2023, với Bầu Cua Online Game bạn có thể chơi cùng bạn bè, chỉnh sửa mã nguồn để trò chơi thêm hay hoặc sinh động hơn và có thể tạo một máy chủ của riêng bạn để chơi một cách riêng tư.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Cách chơi</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Với giao diện đơn giản, bạn có thể vào chơi ngay những phòng đang mở hoặc tự tạo phòng mới cho bạn và người thân.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Để chơi ngay:</span><span style=\" font-size:12pt;\"> Bạn nhấn vào nút &quot;Tìm phòng&quot; ở giao diện trang chủ để tìm những phòng đang mở.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Ở giao diện Tìm phòng, bạn chọn phòng phù hợp rồi nhấn vào nút &quot;Vào phòng&quot; nằm bên phải của dòng phòng đó.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Để tạo phòng</span><span style=\" font-size:12pt;\">: Bạn được lựa chọn làm Người chơi hoặc Nhà cái. Với việc làm người chơi, phòng đó sẽ mặc định Nhà cái là bot và sẽ tự động chơi nếu đủ người chơi. Nếu bạn chọn Nhà cái, phòng đó sẽ được tạo dưới dạng 0 người chơi trong phòng và bạn có quyền bắt đầu chơi khi có ít nhất 1 người chơi.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Sau khi chọn làm Người chơi hoặc Nhà cái, bạn sẽ được yêu cầu cung cấp Tên phòng và Số người chơi tối đa trong 1 phòng. Hiện tại trò chơi chỉ hỗ trợ tối đa 20 người trong 1 phòng, bạn có thể chỉnh sửa giới hạn ở máy chủ của riêng bạn. ID của phòng sẽ được tạo ngẫu nhiên và không bị trùng với phòng khác.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Sau khi đã tạo phòng hoặc vào phòng, bạn sẽ được chuyển đến phòng chờ để chờ tất cả người chơi sẵn sàng hoặc để chờ đủ người trong phòng nếu Nhà cái phòng của bạn là bot.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Khi tất cả đã sẵn sàng và phòng bắt đầu chơi, bạn sẽ được chuyển đến trang lựa chọn, sẽ có 6 lựa chọn là Bầu, Cua, Tôm, Cá, Gà, Hổ theo kiểu chơi tiêu chuẩn, lưu ý rằng mỗi con vật chỉ được chọn 1 lần.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Sau khi chọn bạn hãy nhấn Khóa, lúc này phòng sẽ đợi đến khi tất cả đều khóa thì mới bắt đầu tung xúc xắc.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Khi đã chọn xong bạn sẽ được chuyển đến trang tung xúc xắc, hình 2D của xúc xắc được tung sẽ hiện trên màn hình sau ít giây và cả chữ của chúng, bạn sẽ được biết mình thắng hay thua và số tiền (MHPoint) của bạn sẽ được cộng hoặc giảm tự động.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Sau khi nhận được kết quả, nếu bạn muốn chơi tiếp có thể nhấn vào nút Chơi lại ở góc trái cuối màn hình, nút này giống như nút Sẵn sàng, sẽ yêu cầu tất cả người chơi đều nhấn thì mới bắt đầu ván mới. Nếu bạn không muốn chơi nữa, có thể nhấn nút &quot;X&quot; ở góc trên cùng bên phải màn hình, lúc này bạn sẽ được tự động chuyển về màn hình chính.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Những Quy ước</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Tiền tệ sẽ có kí hiệu là MHPoint và không thể đổi qua tiền thật và ngược lại.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Trò chơi không yêu cầu bạn cung cấp thông tin nhạy cảm lên trò chơi và bạn được khuyến khích không nên tung thông tin nhạy cảm của mình lên trò chơi bằng bất kì giá nào.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Mọi thông tin về người chơi trên trò chơi đều có thể thay đổi trong tệp tin customize.json, bạn có thể thay đổi tùy thích.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Số tiền của bạn sẽ được làm mới sau khi bạn thoát phòng chơi gần nhất, kể cả khi số MHPoint của bạn về con số 0.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Máy chủ được cung cấp bởi MHP miễn phí cho người dùng và sẽ không yêu cầu bạn cung cấp bất kì khoản chi phí nào, MHP chỉ mong các bạn sẽ tiếp tục ủng hộ (Một cốc cafe hoặc chia sẻ rộng rãi) để nhóm có thể tiếp tục phát triển.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Bạn có thể tạo máy chủ của riêng mình nếu bạn thấy máy chủ public chưa được tốt, nhưng mong bạn sẽ không xóa dòng Credit của bọn mình vì công sức của cả nhóm bỏ ra là khá nhiều 💖</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Các bạn có thể đóng gói ứng dụng thành tệp tin .exe, nhưng nhóm mình </span><span style=\" font-size:12pt; font-weight:600;\">sẽ không chịu trách nhiệm</span><span style=\" font-size:12pt;\"> với những hành vi chèn mã độc vào tệp tin .exe và chia sẻ dưới danh nghĩa là ứng dụng của bọn mình. Trò chơi của bọn mình là hoàn toàn mã nguồn mở và sẽ luôn luôn (khá chắc) là như vậy.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Mục đích của trò chơi này là để giải trí với gia đình và bạn bè những ngày Tết, vui lòng không lợi dụng để trục lợi cá nhân.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Official Game Link</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Bản mới nhất của trò chơi sẽ luôn được cập nhật trên trang Github của MHP0920.</span></p></body></html>"))